############################################################################
############################################################################

Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/lictransfer.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"


    - &Org1
        Name: AppleeMSP
        ID: AppleeMSP
        MSPDir: crypto-config/peerOrganizations/Applee.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AppleeMSP.admin', 'AppleeMSP.peer', 'AppleeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AppleeMSP.admin', 'AppleeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AppleeMSP.admin')"

        AnchorPeers:
            - Host: peer0.Applee.com
              Port: 7051

    - &Org2
        Name: ibmmMSP
        ID: ibmmMSP
        MSPDir: crypto-config/peerOrganizations/ibmm.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ibmmMSP.admin', 'ibmmMSP.peer', 'ibmmMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ibmmMSP.admin', 'ibmmMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ibmmMSP.admin')"

        AnchorPeers:
            - Host: peer0.ibmm.com
              Port: 7351

    - &Org3
        Name: oracleeMSP
        ID: oracleeMSP
        MSPDir: crypto-config/peerOrganizations/oraclee.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('oracleeMSP.admin', 'oracleeMSP.peer', 'oracleeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('oracleeMSP.admin', 'oracleeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('oracleeMSP.admin')"

        AnchorPeers:
            - Host: peer0.oraclee.com
              Port: 7151

    - &Org4
        Name: microsofttMSP
        ID: microsofttMSP
        MSPDir: crypto-config/peerOrganizations/microsoftt.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('microsofttMSP.admin', 'microsofttMSP.peer', 'microsofttMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('microsofttMSP.admin', 'microsofttMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('microsofttMSP.admin')"

        AnchorPeers:
            - Host: peer0.microsoftt.com
              Port: 7251

    - &Org5
        Name: googleeMSP
        ID: googleeMSP
        MSPDir: crypto-config/peerOrganizations/googlee.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('googleeMSP.admin', 'googleeMSP.peer', 'googleeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('googleeMSP.admin', 'googleeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('googleeMSP.admin')"

        AnchorPeers:
            - Host: peer0.googlee.com
              Port: 7451

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.lictransfer.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#   CHANNEL
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta

            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    FiveOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Org4
                    - *Org5

    FiveOrgsChannel:
        Consortium: LicenseConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults

            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Org4
                - *Org5

            Capabilities:
                <<: *ApplicationCapabilities

  